name: hemoglobin_guardian
description: "貧血リスクを簡易チェック＆AIアドバイスを行うアプリ"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.6
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.32.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path_provider_windows: ^2.2.1
  sqflite: ^2.3.2
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.0
  path: ^1.8.3
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
  go_router: ^13.0.1
  google_mlkit_commons: ^0.9.0
  google_mlkit_text_recognition: ^0.14.0
  google_mlkit_image_labeling: ^0.13.0
  google_mlkit_object_detection: ^0.14.0
  google_mlkit_face_detection: ^0.12.0
  google_mlkit_pose_detection: ^0.13.0
  google_mlkit_digital_ink_recognition: ^0.13.0
  google_mlkit_language_id: ^0.12.0
  google_mlkit_translation: ^0.12.0
  google_mlkit_entity_extraction: ^0.14.0
  google_mlkit_smart_reply: ^0.12.0
  google_mlkit_barcode_scanning: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  fake_cloud_firestore: ^2.4.8
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - test_assets/ 