steps:
# Dockerイメージのビルド
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/hemoglobin-backend/api:${SHORT_SHA}', '.']

# イメージのプッシュ
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/hemoglobin-backend/api:${SHORT_SHA}']

# Cloud Runへのデプロイ
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'hemoglobin-backend'
  - '--image'
  - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/hemoglobin-backend/api:${SHORT_SHA}'
  - '--region'
  - 'asia-northeast1'
  - '--platform'
  - 'managed'
  # ポート設定
  - '--port'
  - '8080'
  # リソース設定
  - '--memory'
  - '1Gi'
  - '--cpu'
  - '1'
  # オートスケーリング設定
  - '--min-instances'
  - '0'
  - '--max-instances'
  - '10'
  - '--concurrency'
  - '80'
  # コールドスタート対策
  - '--cpu-boost'
  - '--startup-cpu-boost'
  # タイムアウト設定
  - '--timeout'
  - '300s'
  # ヘルスチェック設定
  - '--use-http2'
  - '--http-health-check'
  - '--health-check-path'
  - '/health'
  - '--health-check-timeout'
  - '5s'
  - '--health-check-interval'
  - '15s'
  # 環境変数とシークレット
  - '--env-vars-file'
  - 'cloud_run_env.yaml'
  - '--service-account'
  - 'hemoglobin-backend@${PROJECT_ID}.iam.gserviceaccount.com'
  - '--allow-unauthenticated'
  - '--set-secrets'
  - 'FIREBASE_CREDENTIALS=hemoglobin-firebase-credentials:latest,GOOGLE_APPLICATION_CREDENTIALS=hemoglobin-gcp-credentials:latest'
  # コンテナ起動設定
  - '--execution-environment'
  - 'gen2'
  - '--container-command'
  - 'python'
  - '--container-args'
  - 'main.py'
  # VPCコネクタ設定（必要な場合）
  # - '--vpc-connector'
  # - 'hemoglobin-vpc-connector'

# タグ付け
images:
- 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/hemoglobin-backend/api:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # ビルド時のマシンタイプ

timeout: '1800s'  # ビルドタイムアウト

substitutions:
  _REGION: asia-northeast1
  _SERVICE_NAME: hemoglobin-backend
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "10"
  _MEMORY: "1Gi"
  _CPU: "1" 